### ISSUE TITLE
[Request] Adding more style Pincode Keypad

### ISSUE THREAD

**Issue by netuserxda** [indecisivemal/CleanLockscreen#1]
Hi,

I love your module, it make Pincode Pad look neat and clean, thanks so much :)

I had a request is it possible to add some style to the keypad, for now on samsung TW it is kinda boring small square.  I like how it is on iPhone or on HTC.  Is there anyway to implement some theming to it ?

Thanks a lot :)

**Comment by half-duplex** [comment]
If I have some time I'll look into it, but it's a bit beyond what I know how to do with xposed. If you're code-inclined you're welcome to submit a PR.

**Comment by netuserxda** [comment]
I have 0 knowledge of Java :( so sadly i wont be able to do it, but i am willing to learn or help you beta test if you need it.

**Comment by abhi007john** [comment]
I would love To use this but unfortunately this doesn't work on my device

Xperia L C2104
Rooted and Bootloader Unlocked
Stock Rom JB 4.2.2

Kindly see if you're able to do something

**Comment by half-duplex** [comment]
Android 5 changes the glow to circular, which puts this even farther out of scope for this module.
