### ISSUE TITLE
Can still see circle around lock icon

### ISSUE THREAD

**Issue by Expyron** [indecisivemal/CleanLockscreen#2]
Hi,

I just have one small issue with this module, the circle that is supposed to be around the lock icon is still visible, even when the lock icon is hidden.

You can see it clearly at the bottom of the screenshot. The circle is partly transparent and slowly expanding and contracting, as is usual on CM.

This doesn't always happen, for example when the phone first boots the circle is correctly hidden, but almost every time the phone is locked afterwards, I can see the circle.

I am using the latest CM 12.1 nightlies on a Xperia Z3C and CleanLockscreen 1.5 from Xposed module repository.

Thank you

![screenshot_2015-05-26-20-55-23](https://cloud.githubusercontent.com/assets/5100376/7822269/4d4eef7a-03ec-11e5-883d-efb5d2f52368.png)

**Comment by half-duplex** [comment]
Hmm. The ring is a cyanogenmod addition, but I don't see any interesting differences in their [layout](https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.0/packages/SystemUI/res/layout/keyguard_bottom_area.xml#L60)...

**Comment by Expyron** [comment]
Found it.

The ring is actually an indication that a trust agent (e.g. Smart Lock) is activated.

The code from CM is [here](https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.1/packages/SystemUI/src/com/android/systemui/statusbar/phone/TrustDrawable.java) and [here](https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.1/packages/SystemUI/src/com/android/systemui/statusbar/phone/KeyguardBottomAreaView.java#L204).

Since I'm not really using a trust agent, I disabled Smart Lock, and the ring doesn't appear any more.

Feel free to fix it (or not), at least now you know.

**Comment by half-duplex** [comment]
Thanks for figuring out what was adding it.
That's one annoying circle, but it should be gone in 1.6 (uploading in a few minutes).

**Comment by Expyron** [comment]
Wow, that was fast. Thanks for fixing it :)

Can confirm it's working properly on 1.6.
